"""add role to users and owner_id to jobs

Revision ID: 51e2c9cc68eb
Revises: 103f9c219ac3
Create Date: 2025-10-03 09:21:36.163598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e2c9cc68eb'
down_revision: Union[str, Sequence[str], None] = '103f9c219ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('job_seeker', 'employer', name='user_role', native_enum=False), server_default='job_seeker', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
