"""add revoked_tokens table

Revision ID: 6a6326430a95
Revises: 6f019b31165c
Create Date: 2025-10-02 11:30:36.357156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6326430a95'
down_revision: Union[str, Sequence[str], None] = '6f019b31165c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'jobs', ['link'])
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='unique')
    op.alter_column('jobs', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
